### ISSUE TITLE
Go での業務開発を体験してみて

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#10]
## TL;DR

* foo
* bar
* baz

## 何についてか / About

ref: link, link

## 経緯 / History

1.
1.
1.
1.
1.
1.

## 結論 / Conclusion

* foo
* bar
* baz

**Comment by kachick** [comment]
結構な期間やってたんだけど、自分で趣味でなんか作ってみるみたいな使い方してなかったから今パッと書き出せと言われるとどうだろうか？

悪いというか、良さをスポイルしているように感じたのは自分がよくわかってないクリーンアーキテクチャ周りをこねこねしてたとき。nullable の扱いがそんな厳しくないのでコンパイル通っても動かしてパニックとか多くてうーんだった。
後はGoで完結せずにCのライブラリ組み込んで使わなきゃいけなくなってたときとか・・・CGO_ENABLEDが出てくると、なんで今Go使ってんだっっけ？みたいな暗澹たる気持ちになった。
後はLSPがなんか重くなりやすかった https://github.com/kachick/times_kachick/issues/151

ビルドが早いとか便利な標準ライブラリが一杯あるとかとにかく開発環境全体での体験は良かった気がする。
コンパイル通れば大体 typo とか気にしなくても良いのは気持ちが良い。
ちょっと疑問に思ってたコードジェネレーターも、 https://github.com/volatiletech/sqlboiler の感触がとても良かったので特段不便に感じる事は無かった。

**Comment by pankona** [comment]
最近は「値を入れ忘れてヌルで死にがち」っぽい匂いがするところに exhaustruct って lint を入れてヌルになるのを防いだりもしてます。とはいえ lint でしかないので、この手のはコンパイル時にわかってほしさはある。

**Comment by kachick** [comment]
こないだリポジトリにイイね付けてるの見たので自分も前から欲しかったやつやとvet経由で使ったり調べてみたんだけど、とにかく瞬間も空の存在を許さないっぽいからjsonとかのアンマーシャルで先に空のstrut作るパターンと相性悪い気がしたけどどうなんや……？

**Comment by kachick** [comment]
尚実はGoのどこでも動くっぽい特性が、クセの強いnixosとも相性が良い感じで最近便利に使わせてもらってました

**Comment by pankona** [comment]
ところどころだけコメントで効かすやり方があって、そのやり方だと便利かも。全体に効かすやつだといったん空にしたいときとか不便やな

// exhaustruct:enforce

って、ここだけ効かしたいんやってところにコメントするやり方が便利かも

**Comment by kachick** [comment]
あ、コメント効くんだ。しかしそれなら部分解除したいなー、どこで死ぬかわかってるならそれは関数に切り出すとかテストとかの方がいい気が……

コメントで部分解除できるならアンマーシャル系だけ外すの良いかも

**Comment by kachick** [comment]
//exhaustruct:ignore - ignore structure during linting

普通にあった
