### ISSUE TITLE
2021-06-20 - `愚者は経験に学び、賢者は歴史に学ぶ` は、既に発生した個人の経験や学びを否定してはいないっぽい

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#130]
よく引き合いに出されるけど、実際にはろくな出典が無かったり、むしろ本来逆のことを言ってたみたいな名言・格言は多いと思う。
全部疑ってたら流石にキリがないので、自分の場合は「自分の感性に反しているワードとか、その時都合の悪いワードに関しては出典を調べる」というちょっと小狡い感じの習慣付けをしている。

この手の話でよく知られている物の一つは、 `情けは人のためならず` では無いか。

[文化庁月報 平成24年3月号(No.522)](https://www.bunka.go.jp/pr/publish/bunkachou_geppou/2012_03/series_08/series_08.html)

>　「彼がどんなに落ち込んでいても，厳しく接した方がいいよ。情けは人のためならずって言うだろう。」……このような「情けは人のためならず」の使い方は本来の意味と合っていません。元の意味を確かめてみましょう。
問1　「情けは人のためならず」は，本来どのような意味なのでしょうか。
答　「情けは人のためならず」とは，人に対して情けを掛けておけば，巡り巡って自分に良い報いが返ってくるという意味の言葉です。

誰かが勝手な解釈をしたというよりは、日本語の難しさみたいなところに起因してそうな解説がある。

>この言葉を本来とは違う意味で理解してしまうのは，「ためならず」の解釈を誤ってしまうからだと考えられます。もし「情けは人のためにならず」というのであれば，「その人のためにならない」と受け取れるでしょう。しかし，「人のためならず」の「ならず」は，〔断定の「なり」〕＋〔打ち消しの「ず」〕ですから，「である＋ない＝～でない」という意味になり，「人のためでない（＝自分のためである）」と読み取る必要があります。ここのところがはっきりしないことが「人のためにならない」と解釈する人を増やしている理由だと考えられます。

エンジニア向けだと、 `推測するな、計測せよ` に対してQiitaに気になる記事が上がってたけどどうなのだろうか。

[「推測するな、計測せよ」を推測するな](https://qiita.com/e99h2121/items/e8f899756b21b0414835) 

>バカみたいに読みやすくして、計測できてから、初めて速度の最適化に進めるのよ、ということ。何だ別に、「憶測で物を言うな」っていう話でもなさそうだなという、いかにもな寓話が勝手に一人歩いていたようなフレーズ、「推測するな、計測せよ」でした。

 `最適化をする際には計測しながらしましょうね` という点は特に変わらなさそうなので、ふむ、やっぱりそうですか・・・面倒だけどそらそうだよなーという感じである。

個人的に近年一番調べて良かったなと思ったのは、ビスマルクの格言で `愚者は経験に学び、賢者は歴史に学ぶ` というヤツだ。
個人としての経験や積み重ねを全て否定されてる感じがして「やりにくいなぁ」と感じていたのだが、別にそういうわけでもないのかなと思った。

[愚者は経験に学び、賢者は歴史に学ぶー翻訳の味ー](https://sonarmc.com/wordpress/site36/2015/12/25/%E6%84%9A%E8%80%85%E3%81%AF%E7%B5%8C%E9%A8%93%E3%81%AB%E5%AD%A6%E3%81%B3%E3%80%81%E8%B3%A2%E8%80%85%E3%81%AF%E6%AD%B4%E5%8F%B2%E3%81%AB%E5%AD%A6%E3%81%B6%E3%83%BC%E7%BF%BB%E8%A8%B3%E3%81%AE%E5%91%B3/)

>原文の直訳は『愚者だけが自分の経験から学ぶと信じている。私はむしろ、最初から自分の誤りを避けるため、他人の経験から学ぶのを好む。』となっているそうだ。因みに通常使われているのは英語版『Fools say they learn from experience; I prefer to learn from the experience of others.』の訳なのだが、別段”ヒストリー”の単語が入っていない。こういうのは誤訳というより『超』訳とでもいうべきか。

1. 悪い経験を無駄に重ねたりするのは愚かな事なので、最初に過去事例とか歴史を調べましょう
2. 自分で経験した事からすら何も学べないというのはむしろ最悪

と解釈した。これならわかる、あースッキリ。

**Comment by ohbarye** [comment]
> ちょっと小狡い感じの習慣付け

僕もちまちまメモしてるのでめっちゃ分かる！

[https://scrapbox.io/ohbarye/現在では否定されている、また懐疑的な説](https://scrapbox.io/ohbarye/%E7%8F%BE%E5%9C%A8%E3%81%A7%E3%81%AF%E5%90%A6%E5%AE%9A%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%80%81%E3%81%BE%E3%81%9F%E6%87%90%E7%96%91%E7%9A%84%E3%81%AA%E8%AA%AC)

_ゆでガエル_ とか _割れ窓_ とかも実際の会話や議論でよく出てきて「 💭 言わんとすることはわかるが…」と思いつつたいてい本筋と関係ないので黙ってきました。心の中では 🤪

**Comment by kachick** [comment]
流石！いっぱい集めてありますね〜 😮 

* `茹でガエル` は @pankona さんが「違っていること分かった上で愛用している」印象があった 🐸 
* `マズローの着想は科学的な厳密さの欠如により多々批判されている` そうなんですよね、「モチベーション」とか「ティール組織」辺りを調べてた時に知りました。ただこいつは心理学みたいに「嘘か真か証明できない」類の話ではあると思うので、使ってる方に対して敢えて突っ込むような事もしないようにはしています。 🙈 
* `ふたこぶラクダ` はそもそもその単語を聞いたことすら無いな・・・調べてみます！ 🐫 
* `『神は耐えられない試練は与えられない』の、大事な大事な続きは『試練と共に、それに耐えられるよう逃れる道をも備えていてくださいます。』です。` おー、これはとても大事ですね・・・全部逃げたい 💨  確かに、`後に続く大事なパートが省略される` パターンもありますよね。 `天は人の上に人を造らず` で、`されば賢人と愚人との別は、学ぶと学ばざるとに由って出来るものなり` までを省いちゃってるとか。 🤷‍♂️

**Comment by pankona** [comment]
茹でガエル、一番好きなカエルです！

**Comment by pankona** [comment]
後のフレーズが省略されるものとして思いついたのは、ガガーリンの「地球は青かった」ですかね！

**Comment by kachick** [comment]
https://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%BC%E3%83%AA%E3%82%A4%E3%83%BB%E3%82%AC%E3%82%AC%E3%83%BC%E3%83%AA%E3%83%B3#%E3%80%8C%E5%9C%B0%E7%90%83%E3%81%AF%E9%9D%92%E3%81%8B%E3%81%A3%E3%81%9F%E3%80%8D

<img width="1425" alt="screen_shot 2021-06-20 13 44 09" src="https://user-images.githubusercontent.com/1180335/122662399-9d26d200-d1cd-11eb-8689-1f7d85053024.png">

>空はとても暗かった。一方、地球は青みがかっていた

ってやつ？ `後のフレーズが省略` なのだろうかこれは・・・？ 🤔 
まぁ、やっぱり「短い言葉のほうが強い」から、どっかで編集されちゃったんですかね 🌎 

https://en.wikipedia.org/wiki/Yuri_Gagarin

English の方は、むしろその辺りの section 毎見当たらない気がするんだけども・・・

**Comment by kachick** [comment]
>割れ窓

自分もこれ眉唾みたいな話をどっかで聞いてからほーんそうなんかと思ってたけど、 https://github.com/actions/starter-workflows/issues がスパム放置してたらどんどんスパム天国みたいになってるの見るとやっぱそうなのでは感が否めない
