### ISSUE TITLE
Chromebook って実際どうなのだろうか？

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#139]
前からちょくちょくあったけれど、最近叔父が「PCの調子が悪い」と言ってよく電話なりで聞いてくる・・・が、そんなこと言われてもわかるわけないのである。 🤷‍♂️ 
どうしても邪険にする感じになってしまうのだけど、話を聞いているとなんかマルウェアが幾つか入っててもおかしくなさそうな雰囲気なのでちょっと放置も気が引ける。

10年とまではいかなかった気がするけど相当前に3〜4万ぐらいで買ったHPのノートPCだと思う。値段的にも年数的にも単純に限界なんではと思っているが、機種選定とかセットアップとかを自分がしたこともあって「何でも聞けばわかるだろ」と思われてる感があってまずったなーと思っている・・・つら・・・

叔父の用途的に

* ローカルデバイスとの接続系不要
* Webブラウジングしかしない
* オフィスソフトも別に使わない
* 高いのは無理(というかそもそも新規に出費したくないぐらい)
* セキュリティには気をつけたい

ということらしく、なんかそれって完全に `Chromebook` 案件では？ と思ってしまった。
思ってしまったし口にもしてしまったのだけれど、自分が触ったことすら無いので本当に良いのかどうかが全くわかってない
なので、なんか安いの買ってみて触ってみて、自分には要らないけれど叔父には向いてそうと思ったらそのままプレゼントしてしまってもいいかなと思った。
これがまたカスタマーサポート化の入り口になるとするとつらいのと、「自分にとっても便利」とか「自分にとっても叔父にとっても向かない」とかなったらどうしようという迷いはあるけども

しかし実際どうなんだろ、本当に安い端末でもまともに動くのかな？

**Comment by kachick** [comment]
ちょうど Lenovo が 6/18~8/1 で 3300円引きキャンペーンをやっていたのと、ラインナップを見た時に 「この値段なら迷ってるほうが無駄だな・・・」と思って買ってしまった。

選んだのは [Lenovo IdeaPad Duet Chromebook](https://www.lenovo.com/jp/ja/notebooks/ideapad/duet-3-series/Lenovo-CT-X636/p/ZA6F0019JP) だ。
まず Lenovo に絞った。 というのも #7 で Windows 端末を買うとしたら Think Pad にしようかなと思っているのでどうせなら最近のLenovo製品触っとこうかなと思ったのと、2014年に買った [YOGA TABLET 8](https://www.lenovo.com/jp/ja/tablets/android-tablets/yoga-tablets-series/Yoga-Tablet-8/p/yoga-tablet-8) が値段の割に良かったなーという印象が合ったからだ。
Lenovo == 現在は中国企業ということで色々大丈夫なのか疑惑は拭えないのだけど・・・ https://gigazine.net/news/20180920-lenovo-backdoor-in-china/

Lenovo の中で Chromebook は4種類ぐらいあるようだったのだけれど

[IdeaPad Flex550i Chromebook](https://www.lenovo.com/jp/ja/notebooks/ideapad/flex-5-series/IdeaPad-F5-CB-13CML-05/p/88IPFC51448) => 在庫切れ
[Lenovo Chromebook S330](https://www.lenovo.com/jp/ja/notebooks/lenovo/lenovo-n-series/Lenovo-Chromebook-S330/p/88LGCS31095) => 在庫切れ(19,800円！安い！)

ということで、選択肢はこいつと [IdeaPad Slim 350i Chromebook](https://www.lenovo.com/jp/ja/notebooks/ideapad/slim-3-series/IdeaPad-3-CB-11IGL05/p/88IPSC31450) に絞られた
値段は1万円の差なので、単純に「良い方」を選びたかったのだけれど、どうもこの2モデルはコンセプトが大きく違ってそうで迷った。 `Lenovo IdeaPad Duet Chromebook` は セパレート型で画面も小さめということで、用途的に叔父に向いて無さそうだから最初除外しようかと思った。が、 `IdeaPad Slim 350i Chromebook` は完全にノートPC型に振り切っていてタッチパネルじゃないようで、そうするとAndroid アプリの一部が動くというメリットを全く享受出来無さそうだから実験端末として向いてないなと思った。その点  `Lenovo IdeaPad Duet Chromebook` はタッチパネルな上にキーボード上にタッチパッドも備えて居るようで、USB2.0 Type-Cしかポートが無いことに目をつぶればノートPCとしてもタブレットとしても使えて良いかなーと思った感じだ。CPUはクロック数見れば良いんだけど、今ってその比較で良いんだっけ？が全くわからない。
後はまぁ、ストレージ容量が比較して大きかった。賞を取った人気モデルのようでレビュー数が大差だったという事も背中を押した。

で、いざ購入に進んでみると、クーポンは1つしか適用できないとか言っているのにキャンペーンのクーポンと端末専用のクーポン両方適用できて7000円引きぐらいになった・・・ここまでくると、実際 「Android タブレット」を頑張って探すよりいい選択肢なのでは？まぁ使って無い今のうちに決めつけるのは早いが・・・

<img width="409" alt="screen_shot 2021-06-26 23 27 25" src="https://user-images.githubusercontent.com/1180335/123516496-4a6e7e00-d6d7-11eb-90ff-bfddc6e4c1be.png">

Lenovo の購入フォームはびっくりする程お粗末で不安になった。郵便番号からの住所補完が効かないのはグローバルな作りだろうし仕方ないかとも思ったけど、 郵便番号や電話番号のハイフン(-)をtrimしないでエラーにしたり、メールアドレスにgmailお決まりの「+」が使えないのはマジかよ感がある。いやー、個人商店なりのサイトでうるさいことを言う気はまったくないけども、PCの直販サイトってある意味本業の一種ではないのだろうか・・・ちょっと疑わしくなって、フィッシングサイトじゃないかを再確認してしまった。

なにはともあれ注文が完了したので、とりあえず到着を待つことにする 🍵

**Comment by pankona** [comment]
cloudready というのがあり、chromium ベースの OS (chrome OS もどき)
こういったものを型遅れなノート PC に突っ込んだりすると、ちょっとした chromebook みたいな感じで試せるぞ
https://www.neverware.com/freedownload#intro-text

**Comment by kachick** [comment]
なるほど・・・？10年近く前には自分も型遅れPCにLinux突っ込んで使ったりしてたけど、それの Chromebook もどきという感じですか。良いかも。

でも Google Play ストア 経由でのアプリ導入が出来ないというのは結構痛いというか、完全にブラウザだけの世界では？という気が・・・ｗ

**Comment by kachick** [comment]
その後 Chrome OS Flex が発表されて盛り上がってる界隈だけど、 Chromebook として発売されてる機種はどれもスペックが低いか、コスパがそこまでよくないかでなんかあんま使う気にならなくなってしまった。
プレゼントした叔父も結局操作方法覚える気にならなかったらしく、他の親戚に渡して使ってもらっている。しかしそちらはPCが使えるので別にこれを積極的に使う理由もないみたいな感じ。

古くて死にかけのノートPCがあるので、そこへ Chrome OS Flex いれてみたりしようかなとはちょっと思ってるぐらい

**Comment by kachick** [comment]
>古くて死にかけのノートPCがある

https://github.com/kachick/times_kachick/issues/174

もう一台親に渡してたけどOSが更新されないのでどうしたもんかと思ってた古い Macbook Air が丁度 IdeaPad Duet ぐらいのメモリとストレージなので、Chrome OS Flex の stable が公開されたのを機会に試してみている。
でもこの時に思ったけど、 Google アカウント のパスワードをパスワードマネージャ管理前提で長いものにしていると最初のログイン時に躓くな・・・マネージャ入れる前にまずは Google アカウントに入らないといけないので目視コピペ面倒。
あれ、これって Android デバイスでも同じなのでは・・・？今のスマホ使う時にどうだったのか全く覚えてない

**Comment by kachick** [comment]
なんかLive Bootだとやたら重かったので不安ながらインストールしたらパフォーマンスはマシになった。
しかし・・・当時の日本語配列キーボードなんだけど、英数、かなキーが効かず Shift + Space で IME を切り替えないといけないのが激烈にキツイ。ぐぐるとこの症状一杯出てくるので苦しんだ人多そう。 PoP! OS の時はまだキーボードのリマッピングとか Mozc のカスタマイズとか手段が合ったんだけど、 Chrome OS はその辺代替手段が無さそう。
流石にJIS配列キーボードが全滅というわけでは無いようで、JIS配列キーボードを外付けしたら無変換と変換キーで切り替え出来た。

これは Mac の キーボード自体はを Chrome OS Flex 側で正しく認識できてるけど、そもそも英数系と変換・無変換の違いに対応していない・・・？全く詳しくないけど、このMacの配列は本当にJISなのだろうか。最初から ctrl と capslock の位置が入れ替わってたり便利にチューニングしてありそうなんだけどちょっと裏目に出てしまった。

**Comment by kachick** [comment]
Chrome OS には Linux を入れられるようなのでそっから xmodmap 入れたりでなんとかできんかと思ったけど、標準で備わってる Crostini とやらはコンテナ内実行みたいな感じなのかな？ chroot 技で https://github.com/dnschneid/crouton みたいなのが出てくるけど、そこまでしだしたらもうなんであえて自前ハードに Chrome OS 入れてるのかわかんなくなってくるなと思って最初から Linux ディストリビューション入れることにした。

兎に角軽くないと駄目かなーと Lubuntu にしようかと思ったんだけど、折角時間かけて奮闘したし何種類もクセみたいなの覚えるの嫌だし、最低要件が 2GB と大して多くないことも有るのでこっちにも  PoP! OS 入れることにした。

結果、かなりサクサクで割りと快適に使えそう。
なのは良いけれど、また更にキーボード周りで引っかかった。 その件は https://github.com/kachick/times_kachick/issues/174 へ 🌶️
