### ISSUE TITLE
2021-06-27 - 実用を目的にした読書に関しては、一人読書会をしてそのログかまとめなりを残すようにする

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#140]
#129 で `細かい内容を忘れてしまって居るのでさっき kindle で買い直した。` と書いた [小さなチーム、大きな仕事](https://www.amazon.co.jp/dp/B01NCJVL06) を昨日読み終えた。
うーんやはり良い本だったな！という思いはありつつも、自分の中に「知識」として残り続けて、且つ1年後にも使える部分がどれだけあるのかというと非常に怪しい。よく「知識よりも知恵」とは言うけれど、知恵に昇華するためにはまず知識として蓄えるか、そこまで行かずとも「すぐに引き出せる」ようにしておかないと意味が無いなと思った。

端的に結論を述べた後に具体的な過去事例を述べる形の書籍だったのだけれど、この内過去事例は逐一覚えておけないにしても幾つかの事は将来の自分のために記録しておきたい。

1. 著者の主張
2. 自分がその主張に同意できたかどうか、同意できなかったのなら何故か(これは、自分のその時の考えをログとして残さないと、将来主張点だけ読み返しても誤読しかねないなと思ったため)

と考えた時に、なるほど https://www.flierinc.com/ みたいな書籍の要約サイトとやらが出てくるわけだと思った。ただ、自分の場合「一度はちゃんと通して読みたい、途中で読む気が無くなるような本ならその後の要約も自分には恐らく必要ない」「読んだ内容から、自分にとっての重要点を将来のために残しておきたい」なので、別に多読が目的では無いしちょっと適合しない気もした。

となると、これは「読書会」だなと思った。
職場で何回か読書会が開かれたことがあったけれど、読み進むスピードがどうしても遅くなるのであまり効率的では無いのかなーと思っていた。
しかし自分の興味関心が薄い書籍ですら、最終的に記憶として定着した分量が読書会で読んだ書籍の場合多い気がしている。
これは長期的な事を考えるとかけた時間に対してお得な気もするので、一人読書会をしてみようと思った。開催日時が自由自在というメリットもある。

まぁ、勿論小説とかにこのメソッドを使う気は全然ない。読んでいる時間自体が娯楽な物と、読むことを通じて何かを自分の中に残したい物は区別しようと思った感じだ。

ちょっと気になるのは著作権的な話で、どこまで public に残せるものなのだろうか？ 難しいなら private なメモにしなければいけないだろうけど、ブログなりAmazonのレビューサイトなりでやたら詳細に書いてあるのが問題になったと聞かないし・・・要約サービスは流石になんらかの支払いをしていそうだけれども。

ぐぐったら以下のサイトが上位に出てきた。

* https://hinemoto1231.com/blog/summary-book
* https://uiamu.com/book-introduction-copyright/
* https://uiamu.com/copyright-quote/
* https://www.jbpa.or.jp/copyright.html

うーん、「難しいな」という感想を受ける。特に数が多くなればなるほど怪しい気が・・・

>著者の主張

これが多すぎると翻案権に触れたりする？引用形式を守っても多すぎると問題なようで・・・

>自分がその主張に同意できたかどうか、同意できなかったのなら何故か

これは流石に問題ないようだ。そらそうだろう。

ということで形式は難しいけれど、なんらかの形で残すようにはしたい。

* 詳細な物は private にする
* 強く同意したところと、反対意見を持ったところ3, 4点ぐらいを public にしたりしなかったりする

ぐらいが落とし所な気がした。

**Comment by kachick** [comment]
という宣誓をしたけれど、その後驚くほどやってない。最近読んでるのが殆どマンガで、技術書、実用書、所謂自己啓発感の漂う物にあんま手を伸ばしてなかったんだけど・・・

一気に読まないでパラパラと並列に流し読みすることが多いというのは有るけれど、ノートにまとめるのめっちゃ面倒なのでは・・・？ やはりチャットツールみたいなので複数人でワイガヤやらないと厳しいかも(自律出来ない的な意味で)

https://pankona.github.io/blog/2021/12/13/reading-note/ 自分より半年遅れで同じ様な事言ってるー！ 🤣 

と思ったら https://www.amazon.co.jp/dp/B00H286CHI みたいな本が有るみたい

でもパン粉おじさんも全然続けられてない感だなー。やっぱ難しいなこれ

言うは易し行うは難し(どやぁ)

**Comment by pankona** [comment]
一応 https://github.com/pankona/reading-note というリポジトリを用意していて、読書の記録は残そうとしていた（いた）

**Comment by kachick** [comment]
そこ見ても全然書いてない気がしたんですが、 https://github.com/pankona/reading-note/issues/10 とか結構書いてありましたね！

**Comment by pankona** [comment]
思いの外、読書感想文を書くのはめんどくさかった...
ちなみに Open な issue は「読了したが感想文をまだ書いてないやつリスト」です。あきらめて何も書かずに close したやつもあります... w

**Comment by kachick** [comment]
読んでるそばから忘れていくので、読みながら書くぐらいじゃないと厳しい感・・・

Kindle とかでマーカー使ったこと無いんだけど、ちゃんと使って後で読み直すぐらいがいいんかなー
