### ISSUE TITLE
2021-06-29 - かんばん(kanban) と スクラム(scrum) を混同していた。かんばんはかなり性に合いそう

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#145]
#127 みたいに「スクラム(scrum)はもう懲り懲りでござる！ 🙈 」と悲鳴を上げ続けていたら、近いうちに割とフリースタイルで仕事が出来そうな気配が見えてきた。単純にMustとして降ってくるタスクがひたすら多い日々が続きそうなので、果たしてそれをフリースタイルと呼べるのか疑問ではあるけれど・・・
自分のやりやすいと思うやり方でやらせてもらった時に、本当に現状より何かが良くなるのか？むしろ駄目になってしまう部分は無いのか？みたいなのを実地検証する良い機会だと思う事にした。

そんな中で、自分が全くと言っていいほどわかってない事があったことを知った。「かんばん(kanban)」とやらを、ツールの事、或いはスクラムを内包する管理手法の事だと思っていたのである

* https://www.infoq.com/jp/news/2009/05/kniberg-kanban-v-scrum/
* https://www.atlassian.com/ja/agile/kanban/kanban-vs-scrum
* https://blog.testrail.techmatrix.jp/scrum-kanban-scrumban/
* https://qiita.com/TAKAKING22/items/0a6412e5c3a95a90da50
* https://asana.com/ja/resources/kanban-vs-scrum
* https://www.slideshare.net/kompiro/kanban-vs-scrum-2425317
* https://lean-trenches.com/toyota-kanban-software-kanban/
* https://siderlabs.com/blog/ja/scrum-vs-kanban-in-agile-development/

中でも簡潔に差異をまとめている感のあった https://www.infoq.com/jp/news/2009/05/kniberg-kanban-v-scrum/ の表を引用させてもらう。

<u><strong>相違点</strong></u><br>

スクラム | かんばん
-- | --
イテレーションのタイムボックス化が規定されている。 | イテレーションのタイムボックス化は任意である。設計、リリース、プロセス改善には、個々の速度を使用できる。タイムボックス化の代わりにイベント ドリブン方式が可能である。
チームは、1つのイテレーションで一定量の作業をコミットする。 | コミットメントは任意である。
設計およびプロセス改善に対するデフォルト メトリクスとして開発速度を使用する。 | デフォルト メトリクスとしてリードタイムを使用する。
クロスファンクショナルなチームが規定されている | クロスファンクショナルなチームは任意である。スペシャリストのチームが許可されている。
項目は、1スプリント内で完了できるよう細分化する。 | 項目のサイズは、特に規定されていない。
バーンダウン チャートが規定されている。 | ダイアグラムのタイプは特に規定されていない。
WIPは間接的に制限されている。(スプリント単位) | WIPは直接制限されている。(ワークフローのステート単位)
見積もりが規定されている。 | 見積もりは任意である。
進行中のイテレーションには項目を追加できない。 | 余力のあるときはいつでも新しい項目を追加できる。
スプリント バックログは、1つの特定のチームが所有する。 | かんばんボードは、複数のチームや個人で共有する場合がある。
3つの役割 (プロダクトオーナー/スクラムマスタ/チーム) を規定する。 | いかなる役割も規定しない。
各スプリント間で、スクラムボードはリセットされる。 | かんばんボードは継続的である。
優先順位付けされた製品バックログを規定する。 | 優先順位付けは任意である。

・・・明らかに自分にはかんばんの方が向いていそうだ。
スクラムに合わない部分が多すぎて、制限が緩めのかんばんがマシに感じるというだけかも知れない? 🤔 
いやいや、期間の定まったプロジェクトでは無くて日々の保守運用こなしながら合間を縫ってなんとかエンハンスもしていきたいみたいな状況下では明らかにかんばん優位でしょうよ・・・早く知りたかった 😢  

タイムボックス、項目のサイズ、見積もりが任意という時点でそうそうと大きくうなずき、スクラムボードはスプリントでリセットされるがかんばんボードは継続的というところで 👏 
しかしそれ以上に、 `バックログの優先順位付け` までが任意というのはかなりの驚きだ。個人的にはかなり引っかかる部分の一つだったので、規定のメジャーなフレームワークにこういう形式もあると知れたのは目から鱗だった。とにかく柔軟な感じがするなー、期待大では？

**Comment by kachick** [comment]
https://www.infoq.com/jp/minibooks/kanban-scrum-minibook/ ちょっと気になるけど、無料版pdfのダウンロードに登録とか必要そうで面倒だ・・・
https://www.lulu.com/content/7731694?page=1&pageSize=4 書籍買ってみる？ 👀

**Comment by pankona** [comment]
かんばん仕事術
https://www.oreilly.co.jp/books/9784873117645/

**Comment by kachick** [comment]
ありがとうございます！ https://github.com/kachick/times_kachick/issues/148 で読んでみます・・・！
