### ISSUE TITLE
2023-01-27 - footer なりに git の ref 貼っておくのが好き

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#207]
何にでも一意に定まるソースを挿し込むのが好き。
例えば ruby でいうところの、この revision とか

```console
❯ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
```

git の ref が入るようになっているので、 https://github.com/ruby/ruby/commits/a528908271 みたいにサクッとそのバージョンを見に行ける。
デバッグの時とかこういうの嬉しい。前職でも Sentry のエラーレポートに monorepo の git ref 挿し込んでくれた方が居て、地味に嬉しいんだよなぁと思った。

エンドユーザーには見せたくないと html で表出しないタグとして埋め込んだりはありそう。
ただ view の有るものでこういうのを footer なり目に着くところに入れておくと、バグ報告時に貼ってくれたスクショから簡単に追えたりするので、許されるプロダクトなら全部に入ってて欲しい。
そもそもデプロイに成功したと言われても、見た目に大きな差異が無い時とか何かしらの「手応え」が欲しくなったりする。

ということで、自分の趣味なフロントエンドアプリには入れている。

<img src="https://github.com/mobu-of-the-world/emobu/blob/main/docs/assets/mobu-elm.web.app_(iPhone%20SE).png?raw=true" height=500>

↑ 🦶  の `d097b4f` をクリックすると [repository の対象 ref](https://github.com/mobu-of-the-world/emobu/blob/d097b4f) へ飛ばす。

vite + elm だとこんな感じに埋め込める。

https://github.com/mobu-of-the-world/emobu/blob/35ab8ceb91f86624c758406248b57ab44761221e/vite.config.ts#L1-L19
https://github.com/mobu-of-the-world/emobu/blob/88a7699ec93bea11cfcd3a1252206ea7551886aa/src/main.ts#L11

elm の場合は初期化時に渡す必要があるけれど、 TypeScript+ React でも同様に vite.config.ts を書けば良い。 https://github.com/mobu-of-the-world/mobu/pull/444

GitHub Actions 経由での staging 環境を用意している場合、 ref が差し替わる？(git 未だによくわからない)ので若干手を加える必要がある

https://github.com/mobu-of-the-world/emobu/blob/35ab8ceb91f86624c758406248b57ab44761221e/.github/workflows/firebase-hosting-pull-request.yml#L35-L36

```yaml
      - name: Specify actual commit ref for revisions
        run: echo VITE_COMMIT_REF=${{ github.event.pull_request.head.sha }} > .env
```

**Comment by pankona** [comment]
開発者自身も「ちゃんと最新がデプロイされてんのかな？」って迷わなくて済むので、そういう意味でも便利

**Comment by kachick** [comment]
そうなのよ、手応えがないとね、デプロイした気になれないからね

(ここ20年ほどの設定画面みたいに保存ボタンを押させてくれないやつだと、本当に保存した気になれないお年頃)
