### ISSUE TITLE
2023-07-30 - Chrome 使って一部のリポジトリをページ内検索かけると、表示が何ていうかこう不思議なバグり方をする

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#239]
https://github.com/nix-community/home-manager/blob/f58889c07efa8e1328fdf93dc1796ec2a5c47f38/modules/programs/zsh.nix

みたいに、home-manager のリポジトリでしか今んとこ出くわしてない。
nix 言語 に対する GitHub のカラーリングのバグなのか？しかし FireFox Developer Edition では問題ない

https://github.com/kachick/times_kachick/issues/236 のせいかなーとも思ったんだけど、ブラウザで差異がでるもんか？タイミング的に完全合致かはなんとも

まず黒くハイライトされ、そのままスクロールすると薄皮が剥がれてつきまとうかのように・・・
ブラウザをF5リロードで回復するけれど、その後も発生する。再現率100%だから貴重な症例かもしれんと思いつつ、どうでもいいので治って欲しい

<img width="438" alt="スクリーンショット 2023-07-30 180642" src="https://github.com/kachick/times_kachick/assets/1180335/2e0237e9-678c-4062-a1fb-8e012e8b3af0">
<img width="444" alt="スクリーンショット 2023-07-30 180623" src="https://github.com/kachick/times_kachick/assets/1180335/ab6eda4f-2c1c-45cb-9282-1325c17f62f6">
<img width="430" alt="スクリーンショット 2023-07-30 180629" src="https://github.com/kachick/times_kachick/assets/1180335/f1f34e49-1bf8-4c9a-978b-424efd205bd0">

**Comment by kachick** [comment]
mac + chrome でも発生した。不遇な nix

**Comment by kachick** [comment]
chrome://flags/#enable-experimental-web-platform-features

を 116.0.5845.97 時点で ResetAll しても完治はしない・・・んだけど、なんか発生率が低くなったような気がしなくも無い。

**Comment by kachick** [comment]
edge の 115.0.1901.203 でも発生しないので、、Chromium の問題でも無さそうな・・・

**Comment by pankona** [comment]
deepl の Chrome 拡張いれてるとギッハブの表示が崩れることがある、みたいな記事を最近見た。関係あるか分からないが一応 FYI

**Comment by kachick** [comment]
そ、それっぽい～！ 😂 

`読みながら翻訳のアイコンを表示` を入れた状態のときだけ発生する感じがある・・・

Chrome拡張も疑いはして、自作のやつとかフロント用DevToolsとかは外してみてたんだけど、DeepLはノーマークだったわ・・・
確かに拡張は別のOSでもGoogleアカウント経由でSyncされるもんなぁ

あざます！ 🙏  助かったー

---

[DeepL さんには大変お世話になってきた](https://github.com/kachick/times_kachick/issues/69)けれど、この1年Pro契約して使ってみて別ブラウザとかアカウントからログインしようとするとシビアに弾かれたりクライアント周りが大変不便で、且つPDF翻訳とかのレイアウト維持やOCRは Google 翻訳のほうが精度高いし ChatGPT に翻訳させる方向性も少し気になるのでライセンス更新は切ってしまった。API単位での契約はちょっと気になってる

**Comment by kachick** [comment]
https://christina04.hatenablog.com/entry/deepl-chrome-extension

これや！

二週間前に出てた記事なのか・・・ちゃんと console log に出てたんだ、見た気がするけど、他のに紛れて気づかんかった～

しかしこの症状、言葉で表現するのが難しいからまずDeepLを疑うというか切り分けてからじゃないと検索に当たりづらそうだなー

**Comment by kachick** [comment]
https://support.deepl.com/hc/ja/articles/4407516019218-Availability-of-browser-extensions
https://support.deepl.com/hc/ja/requests/new

<img width="407" alt="スクリーンショット 2023-08-21 094907" src="https://github.com/kachick/times_kachick/assets/1180335/827f37fe-b20d-4973-9cfc-6e139a041f68">

この Chrome 拡張は OSS じゃないっぽいので(拡張全般ソースコードにはアクセス出来るけど)自分も報告しとこうかと思ったけど、その導線でも Pro ライセンスに誘導されてそれ以外の人お断りっぽいのがなんかもうという気持ちにはなる。

**Comment by kachick** [comment]
拡張の設定機能として「ページ全体の翻訳のポップアップウィンドウを非表示にするサイト」というのがあるんだけど、ここへサイトを追加する導線みたいなのが無さ気な気がする。ので、機能単位で落とすしか無い
