### ISSUE TITLE
2023-09-30 - allow-empty な commit を作らずに not diff な状況で git commit するとエラーが出るのを回避しようと `git diff-index --quiet HEAD || git commit ...` をしてたら git diff と異なり touch ですら反応してしまうのに15分ぐらい詰まったけど `git update-index -q --really-refresh` を先に叩いたら解消した

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#251]
全部タイトルに詰めてみた(ラノベっぽい？)

https://stackoverflow.com/questions/34807971/why-does-git-diff-index-head-result-change-for-touched-files-after-git-diff-or-g#comment103750839_34808299
https://github.com/kachick/irb-power_assert/commit/bb2b8d46105065fb7df6fafe302f81c312c0b7b0

**Comment by pankona** [comment]
記事を読まずに記事の内容が分かって便利
