### ISSUE TITLE
2023-11-29 / サポートの方法で "チャット(ボット/AI)" みたいなのしか無いときのがっかり感と、”チャット(人間)” だった時の喜びよ

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#255]
## 前提知識

  - 電話は元から好きじゃない(コールセンターやってたことあるけど)
  - メールも年々苦手になる(得意だと思ってた前前職時代ですら、貴方のメールは冷たすぎると言われたことがある)
  - チャットで済ませるのがなんでも楽(ojichat 的にemojiやリアクションでごまかせる 😄 )

## 本題

なんかのサービスを使って困ったり問い合わせしたり、どうしてもWeb手続きだけで済まずオペレーターへコンタクト取りたい事がある。そんなとき電話対応にリソースを割くのは企業側も避けたいからなのか、電話番号を極力隠してるところが多い。
こっちも電話は好きじゃないのでチャットという選択肢があると飛びつくんだけど、大半が「AI回答」とか言ってる。
ChatGPT登場以前からこういうの多かった気がするけど、これらはこっちの入力した文言を検索してFAQから回答を引っ張り出してくるみたいなのばかりで、本当に役立った事が一度もない。生成AIにWebの海にたゆたう大量の情報から引っ張ってもらってもらうとかではなく1サービスのFAQなんて普通に検索すれば求める情報へたどり着けるし、検索して引っかからないのは最初から回答が用意されてないだけなのだ。
そうすると不便なFAQで且つ担当者へ接続されない謎のボット相手に疲弊させられてしまう。なんであるんだこんなの・・・？

反面、たまにというか本当に担当者がリアルタイムで張り付いててチャット接続できるところもある。
Amazonとかはそうだし、Sony 系のサービス系もこれが多い印象。この手のところはたいていチャットでやり取りした内容を最後にテキストでダウンロードできるようにもしてくれてて便利オブ便利なのだ。
もっと増えてくれないかなー。というか、最終的に担当者へ繋がる方法のないのはチャットじゃなく "チャット画面風FAQ検索窓" とか呼称して欲しい

**Comment by pankona** [comment]
ほしいのは答えじゃなくて、悲しみや怒りの共有だから…

**Comment by kachick** [comment]
ちゃうねん、単純に公式資料とか定型処理で収まらない対応が必要とかでカスタマーサポートへつないでほしいのに、そこが潰されてるのがあかんねん
(全ての枝葉なカスタマー処理までシステム化されてるなら別に自動応答でも構わないけれど、普通そんなとこまで開発はしないので)

なので別にサポートの第一窓口にAIが出てきても良いのかもしれないけれど、基本的にシステムに組み込まれた生成AIってセキュリティ対策も込で許される副作用がすごい少ないでしょ。その点で相性が悪いんだろうなという気はする。
AIが必要と判断したときに、ランダムに発行される非公開窓口URLをこっちへ教えるみたいなのでもあれば違うんだが・・・

**Comment by kachick** [comment]
「必要性をAIに説いて納得させられれば、最終的に人間の担当者へ取り次いでくれる」

こういうAIボットならありなんや
