### ISSUE TITLE
2024-02-12 - 今年になってから新型コロナウイルスに感染してた

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#260]
新型コロナウイルスが流行りだしてからは大体世間一般の対策を取ってきたつもりで、マスクはつける、ワクチンは複数回打つ、具合が悪くなったら抗原検査やらPCR検査をしてみるとこの数年を過ごしてきてたんだけど、ワクチンが効いてたのかなんなのか風邪っぽいときでもずっと陽性反応は出なかった。
世間の扱いがゆるくなってきて自分もそれなりに外出するようになっても全くなので、今年に入ってから最初に風邪っぽいのになったときもどうせちゃうんやろうなと思ってたのに抗原検査キットでバリバリTの線が出てしまった。
よくTの線は薄くでても陽性だから！みたいな事聞いてたけど、そんなレベルではなく試薬が触れた途端に濃い線がビシッと入ったのでちょっとびびった。正直この抗原検査キットというのは当てにならなくて無症状感染とかどっかであったのではとすら思ってたんだけど・・・
しかし厄介なのが、買いだめしていた抗原検査キットがまだ期限内だったのに試薬が乾いてきているのか幾つか試しても全部Cまでいかない。これはCまでいかないときはTまでいこうがいくまいがゆめゆめ信じるなかれということになっているので、仕方ないなーと近所のクリニックに電話相談した上で発熱外来へ
PCR検査的なことやるのかと思ったら、自宅でやるより簡単に結果が出る新型コロナ＋インフルエンザ用の抗原検査みたいなのをやるだけだった。結果はやはり陽性
持病で喘息があるので怖いんですよねーという話をしたところ、１万弱出せば使えるというラゲブリオという薬を５日間飲むことになった。
高いなーとは思ったけれど、案の定というか喘息に引火した。ここ数年は普通の風邪やインフルエンザから喘息に引火する事なかったので、実際に効いてくれたかはわからないけど同じ選択ができるとしたらやっぱお願いする気はする。発熱は最高でも37.5付近で止まり、大まかな症状は6日程度、喘息も含めると14日ぐらいで楽になってきた気はする。もう扱い的に特段縛りはないらしいけど、喘息の咳がおさまりきらなかったので人前に出るまでさらに10日程自粛することにはした。この咳は伝染らないんですよーという話をされても気持ちとしてウッとなりそうだし・・・尚それから更に数日経っても喘息の咳は取り切れてない。つらい

酷い後遺症に悩まされてる感じは今のところ無いので、まぁ2年ぐらい前の段階でのあのおっかなさとくらべれば軽く済んだんだろうなー

そういえば今まで試したことなかったんだけど、今回鼻詰まりがひどくそれが呼吸の苦しさにも影響してたのでうたぐりつつ試してみた鼻うがいがとても良いものだった(医学的にどうなのかはしらない)。面倒なので毎日できる気はしないけど、今後の喘息対策で是非使っていきたい

**Comment by pankona** [comment]
@kachick お大事に！！

**Comment by kachick** [comment]
あざます！
