### ISSUE TITLE
2024-02-21 - GitHub repository の設定をコードとしてどっかのリポジトリで管理したい。勿論そっち更新したら反映させたい

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#263]
所謂 `GitHub Config as code` みたいなのが個人アカウントでも欲しいこと多くて、なんかサクッと出来そうなのが少ないイメージ
private リポジトリの GitHub Actions で起動できるみたいなのが理想的な気はするんだけど(https://github.com/kachick/times_kachick/issues/258 になりやすいか？)、あんましそういうの見ないような。 `gh` cli で出来るとある程度楽になりそうなんだけど、`gh repo edit` での一部 + secret + archive みたいにまばらという印象

後 organization で動くソリューションは多そうなんだけど、 user に紐づくリポジトリでも動いてほしい

候補っぽい物

https://github.com/integrations/terraform-provider-github
https://github.com/github/safe-settings
https://github.com/repository-settings/app
https://github.com/cli/cli/issues/995#issuecomment-634495002 => https://cli.github.com/manual/gh_repo_edit

**Comment by kachick** [comment]
リポジトリの設定は https://docs.github.com/ja/rest/repos/repos?apiVersion=2022-11-28#update-a-repository 経由でやってることだから `gh edit` で対応しているけれど、リポジトリのアクションの設定は https://docs.github.com/ja/rest/actions/permissions?apiVersion=2022-11-28#set-default-workflow-permissions-for-a-repository 経由でやることだからまだ gh cli で対応していないという感じっぽい
gh cli は任意の API 叩きやすいから別に機能としては存在しなくても対応のAPIが存在する事わかってしまえばまぁなんとかなりはする

**Comment by pankona** [comment]
terraform っぽい案件？

**Comment by kachick** [comment]
と、いうのを候補の中に https://github.com/integrations/terraform-provider-github で挙げてあります！ 😤 

でも個人リポジトリ向きじゃない気はしてるんだけどどうなんだろうか。
OSS でそんなに導入されてないイメージだったけど、 asdf のコミュニティ org が https://github.com/asdf-community/infrastructure/blob/1255c905a1b0af000f46902d5a73e1c63597d472/terraform/github/repositories.tf みたいに使いだしてるんだよね
