### ISSUE TITLE
2024-02-21 - Go 1.22 から go.mod の更新には `go mod tidy` ではなく `go get` が推奨されるようになってた

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#265]
そもそも toolchain の事があんまわかってないので知りたいなと https://go.dev/doc/toolchain を流し読みしていたら見つけた。尚 toolchain の事は読んだ後でもあんまよくわかってない

とりあえず手を動かす時の話として、go.mod を更新したい時にこれまでは何も考えずに `go mod tidy -go=1.22` みたいなのを使っていたんだけれど、今後は何も考えずに `go get go@1.22` を使えばいいんだなという事らしい(ほんまか？)

https://github.com/golang/website/commit/65471dac0a55de6881c15b280050b6b1841d4bc3#diff-fbae24fc0956e6f23d35e47544ab43fb87ace38198666f848051ca75269888c5R414-R418

ここで追加されている

```
Before Go 1.21, the suggested way to update a module to a new Go version (say, Go 1.22)
was `go mod tidy -go=1.22`, to make sure that any adjustments
specific to Go 1.22 were made to the `go.mod` at the same time that the
`go` line is updated.
That form is still valid, but the simpler `go get go@1.22` is now preferred.
```

別に go mod tidy が今後駄目というわけでも無いよとは言ってるけど、こっちがおすすめだぜみたいな事添えられたら気になるやん

尚挙動としては同じではなく、どのバージョンの go で走らせるかによるとも思うんだけどこっちだと toolchain の記載を削ってきてた

https://github.com/kachick/selfup/pull/112/commits/23c7f276e67746d3dfd356bb8cab4694c900ff4e

**Comment by kachick** [comment]
こんなとこにこだわるというか引っかかるのはきっと日本人ぐらいで、向こうは心底どうでもいいと思ってるのかもしんねぇ・・・

**Comment by pankona** [comment]
定期的にここを見に来ている (やり方を覚えられない)

**Comment by kachick** [comment]
tldrを面倒で省いているから駄文を毎回読み直す必要があるやつ


(自分だけで40アクセスぐらいは稼いだであろう刺し身さんの https://blog.kyanny.me/entry/2015/02/07/020319 見たらちゃんとtldr書いてあった)

**Comment by kachick** [comment]
>TL;DR

✅

**Comment by pankona** [comment]
ちゃんとしてる
