### ISSUE TITLE
2024-03-08 - ゴミ箱の中にデータを保存・整理するという発想

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#276]
もう20年とか昔だから細かいコンテキストが思い出せないけれど、知人と話をしててWindows PC上のファイルをどう整理しているかみたいな話になった時衝撃的だった。

その人は大事なファイルほごみ箱の中に入れているんだという。
何を言ってるかわからないものの、その行為には技術か宗教哲学に根ざしたなんぞ深い意味でもあるのかと聞くと、いや単にデスクトップの一番見やすいところに必ずアイコンがあって他にフォルダとか作る気にもなれないから大事なものはゴミ箱、他は他と分けているんだとか。

ぼく「え、いやでも何かのはずみに空にしちゃったら・・・その、空になるよね」
彼「ごみ箱を空にしたこと無いし、しなければいいんでしょ」

人間の発想は無限大だなぁと思った

**Comment by pankona** [comment]
ゴミ箱を空にするという仕草が癖になっていたことがあり (linux 使ってるときに無意識に ls しちゃうみたいなノリ)、他人の PC でついそれをやってしまったことがあったのを思い出しました。ゴミ箱はゴミ箱だろ

**Comment by kachick** [comment]
>linux 使ってるときに無意識に ls しちゃう

これは本当にわかる。
そもそもこれがあるから結局GUIの強いOSとかディストリビューションから離れられないのではという気もしていたんだけど、案外ありそうであんまみなかった解決策を最近見っけた。

https://github.com/antonmedv/walk

go で書かれてるので kona の力で強くしていってほしい

**Comment by pankona** [comment]
これ便利そうやな。使ってみよう

**Comment by kachick** [comment]
walk は標準のlsっぽいとこへどんなフィルタかけるかみたいな話っぽいので別に代替出来るというものでもなかった。

**Comment by kachick** [comment]
ずっと vim 系エディタ避けてたけど helix の感触が良くて使い出した。というか画面バシバシ分割していると TUI 以外は厳しく、且つ TUI でモード型じゃない micro はどちらかというとシンプル寄りでコード書くのにデフォルトで不足が多く、且つキーバインドがZellij等々とぶつかりやすい。

そうすると今度は file tree 無いのが厳しかったんで walk 的なの向上させる必要があって、いくつか試した限り群を抜いて良さげだった https://github.com/sxyazi/yazi を使い出した

**Comment by kachick** [comment]
ウィットに富んでそうなコミットログ且つ誰もツッコミを入れていないんだけど https://github.com/antonmedv/walk/commit/f6faf52e8986008af27cf6d746c645ca0c01dfd3 このコミットの目的がよくわかっていない

**Comment by kachick** [comment]
https://github.com/search?q=emitCO2&type=code

![image](https://github.com/user-attachments/assets/538e6496-2f82-4c1b-8244-6dee2c30e869)

そして案外同じ名前で作られているな
