### ISSUE TITLE
2024-04-06 - 重ゲーのルールを超速で読んで整理できるようになりたい

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#283]
10年以上ボドゲやってるのに未だにというか最近の方が老化もあってか重ゲーのルールを読めなくなってきた。
それでいてどうしても欲しいものはどうしても欲しいから買ってしまい、諸悪の根源たる積みゲーが増える一方になってしまう。

遊べば資産、積めば負債

**Comment by pankona** [comment]
「ボドゲを華麗に積むボドゲ」をやってると思えば積むのも楽しいのではないか。枯山水だよ

**Comment by kachick** [comment]
「ボドゲを買うボドゲ」としてエッセンをテーマにしたボドゲがかつてあった。懐かしい https://boardgamegeek.com/boardgame/157088/essen-the-game-spiel13

**Comment by kachick** [comment]
これ結局プレイイメージが無い状態でテキストだけで想起するところから始めるのが大変というのも結構あるんで、最近はまず youtube とかに上がってるインストやらプレイ風景の動画が無いかをさらっと確認してそっちを自動翻訳とかで流し観してからルール読みに入るようにしてはいる。前よりはこれで先に進めやすくはなった

3,40年前とかの古いマニアックなゲームだと中々動画も無かったりするんだけど、そもそもその時代だと今みたいなオモオモゲーがあんま無いから概要把握には苦慮しない(しかしライティングの問題で細部の不明点はめちゃ多い)
