### ISSUE TITLE
2024-04-10 - ケンジントンの SlimBlade Trackball を使うと細かい範囲に着地させたり選択するのが大変

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#285]
8年ほど前に同僚からケンジントンのトラックボール [SlimBlade Trackball 72327JP](https://www.amazon.co.jp/dp/B004QJYBAG) を勧められて使いだしてからハマってしまい、ずっと手放せていない
ゴミが溜まりやすいとか劣化により調子が悪くなってくるとストレスフル、価格が高いとか諸々合っても手放せない。ロジクールの親指トラックボールみたいなのも試してみたけど全然だった。
去年辺りから流石に掃除しても不調が続いていたこともあって、いつかのブラックフライデーで購入した後継機？っぽい [SlimBlade Pro トラックボール K72085JP](https://www.amazon.co.jp/dp/B0C5QP55YX) に差し替えている。

前と較べて良くなかったかはわからないけど、とりあえず同じぐらい手には馴染む
ただ問題はこいつを使って正確に文字列を範囲選択するみたいなのが難しい。ぬるぬる動きすぎて、大体の位置合わせは出来てもピタッと１文字２文字分合わせるみたいなのが大変
これは lishogi で対局する時もそうで、秒読みになるとかなりマスを合わせられない

72327JP 時代はここまでじゃなかった気もするんだよなー
単純に速度調整とか加速の問題かもだけど、遅くするとそれはそれでうっとなるんよな

**Comment by pankona** [comment]
いっときこれでアクション要素の強いゲームに挑んだことがあるけどだいぶ厳しかった。精度を求めるならやっぱりマウスな気はする？

**Comment by kachick** [comment]
ロジクールのやつとかトラックボールマウスみたいなの如何にもマウスとしても使って下さい感にみえるけど、マウスとしてはかなり重くて使いづらかったなー・・・

MacBook の Magic Trackpad はこういう用途でも強いんだけど、利用頻度高いと疲れるのと指の腹がすり減るという・・・

**Comment by kachick** [comment]
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q11290031466

知恵袋が初めて有用だと思えた気もするけど、なるほどこういう用途では親指ボールの方がやりやすいのか・・・？

**Comment by kachick** [comment]
デスクトップでもタッチパッド併用したい気もしつつ、ガジェットを増やしたくない気もする

とりあえず喫緊な感じでも無いから閉じちゃおう
