### ISSUE TITLE
2024-06-12 - 画面分割と己の相性が悪い

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#297]
https://github.com/kachick/dotfiles/pull/623 こないだから何度目かの画面分割にチャレンジしているけどどうも最初のインパクトはいいなぁと思うんだけどその後狭っと感じるので使わなくなりがち。

前にめちゃでかいディスプレイ・・・32ぐらい？を使う機会があったけど、デカすぎて目が疲れたり相性が悪かった。
今は27を使っててほどよい感じがするんだけど、こんぐらいだと今度は分割すると狭く感じる
今思うと32から上は分割で使うの前提だったんだろうか。というか分割で使うならそんぐらいディスプレイ前提とか？

別に分割かっけーとかじゃなくて常にあれやこれやの window 切り替えるの面倒なのでなんかしら楽にしたいだけなんだけど、どうすればしっくり来るんや。
でかいディスプレイ試したい気もするけど、それでやっぱ分割しても合わないなとかなったら邪魔過ぎる・・・

**Comment by kachick** [comment]
画面分割というよりタイル型ウィンドウマネージャについてだった。要は広く使いたいときにも狭く使わされがちだったからぐあーとなってただけで、使う機能を絞った状態＆これまでの環境を維持(Hyprlandは使わずに GNOME+pop-shell とかから使う)したとこから始められるようにしたらかなり便利だった

キーバインドを覚えられない => キーをカスタムするというか、自分が使わないけどつい押しちゃう機能は一旦削る。そしてデフォルトがシンプルな物を使うようにする

広く使いたい事が多い => ウィンドウの最小化に関するキーバインドは忘れて良い、どうせ閉じるのは覚えているし、最小化した物を持っかい広げるのが面倒。それよりは最大化のトグル方法を覚えておいてひたすら並べるか最大化するかだけで暮らす

ワークスペース => 慣れると便利。アプリケーション単位でアサイン出来るかどうかはものによるのとカスタマイズし切るのが大変そうなので、よく使う一部だけ設定しとくとよさげ。自分はとりあえず音楽再生系だけワークスペース分けたけど、これだけでも便利

キーバインドの conflict は厄介なので、思い切ってばんばん削るようにした。こういう時に config を管理しやすいソフトウェアは良い。最初しばらくKDEに落ち着いてたけどカスタマイズが厄介なのでGNOMEにしたら弄りやすくて驚いた。そしてこれが本当にNixOSとの相性が良い

Windows に関しては GlazeWM の2.x時代に挫折してkomorebiにいってそれも使わなくなってたんだけど、GlazeWM の3.xがリリースされたのでまた試してみたら、デフォルトがSuperかAltかの違い以外は大体同じ感覚で使えそうな気がしている。
数が増えた時にも自分で分割方向指定してやらない限り全部一方にしか分割されていかないのだけなんとかしたくはあるけど、これはi3系ってのがそもそもそういうものなのかなー https://github.com/glzr-io/glazewm/issues/497#issuecomment-1876227433, https://github.com/glzr-io/glazewm/blob/12d92059cdfd675d9d9428f33f2b606f4143153f/README.md#L301

**Comment by pankona** [comment]
Windows で使えるタイル型ウィンドウマネージャ探してたので助かるー

**Comment by kachick** [comment]
>Windows で使える

Windowsとかいう名前にしておいてWindows一杯開いた時の管理が特に便利でも無いの釈然としないぜ！

---

Linux で今使ってるやつだと pop-shell と Hyprland がどっちもデフォルト Modifier が Super(Windowsキー)でそういうもんかと思ってたんだけど、i3wmのデフォルトがAltなのとWindowsだとWindowsキーを上書きしきれないという話があるからかWindowsだとGlazeWMもkomorebi(というか担っているwhkd)もAltをデフォルトにしている。
僅かな差やろと思ってたんだけど、微妙に間違えること多くて大変だ。合わせるならいじりやすいLinux側のキーバインドをAltに変える方向なのか～？
これはWindowsのコピペCtrl+C、Ctrl+Vに慣れてるとターミナルエミュレータではbashに確保されたのと衝突避けるためにCtrl+ShiftがModifierになるのと列んで嫌な感じ

**Comment by kachick** [comment]
Windows ならそもそも virtual desktop を活用できるようにするとこから始めた方が筋が良い気もしつつ、Win+Tabは便利ながらアプリの移動にこの画面からマウス操作が必要となると気軽に使う気になれない。
そして GlazeWM の workspace とかはこの desktop 単位ではない別概念っぽいので組み合わせを自分で考えていくのが億劫だ・・・

**Comment by kachick** [comment]
色々現状の候補というのはあるにはあってもちろん感謝なんだけれど、とりあえず https://github.com/microsoft/PowerToys/issues/4 に vote が1万ぐらい集まったらオフィシャルにやってくれるのだろうか

**Comment by kachick** [comment]
https://github.com/microsoft/PowerToys/issues/37
https://github.com/microsoft/PowerToys/issues/5
https://github.com/microsoft/PowerToys/issues/2694
https://github.com/microsoft/PowerToys/issues/4135
https://github.com/microsoft/PowerToys/issues/31389

まだまだいっぱい有りそう。やっぱ今だと一番最初に見に行く先はやっぱ PowerToys だよなぁ
