### ISSUE TITLE
2024-06-19 - 夏場の生ゴミ tmpdir

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#298]
Problem
---

今の場所だと生ゴミを出せる収集日は週二回
常時出せるわけではないので、3~4日間生ゴミを自宅で保管しないといけない

How(Failed)
---

これから更に暑くなるんだろうけれど、今時点で既に暑くてベランダに出してるとコバエがやばかった
わさび成分による貼る防虫剤みたいなのをゴミ箱蓋に貼ってたけれど、1ヶ月持つとあるが効果を感じられたのは2週間だけ。それでいて1枚1000円するからランニングコストがお高い
そもそも虫は防げても普通に腐るから、匂いの問題も出てくる

How(Idea)
---

冷凍庫保管は若干抵抗有るのとスペースが足りない

clean box というゴミ箱専用冷凍庫 https://www.sanka.ne.jp/kaden/products/ncb1.html があって凄い良さそうなんだけど6万円ぐらいする

コンポストは土化してくれるといっても土の使い道が特に無いのと、それなりに高いかミミズなり飼育が必要そうなイメージ

How(In progress)
---

というとこを経て、家に転がってた最近使う機会もないクーラーボックス(15L程度)を活用してみることにした
今まであった保冷剤は一晩持たないラインだったので、長時間持つらしい COOLER SHOCK を買ってみた。Mサイズ4個セットで5000円程度と結構な出費。これを2枚ずつ使ってみる予定（尚Lサイズだとデカすぎて今のクーラーボックスにも、うちの冷凍庫空きスペースにも入らない。)
見えないところの温度が気になるのと交換忘れそうなので SwitchBot の 防水温湿度計 も突っ込んだ。 https://www.switchbot.jp/products/switchbot-indoor-outdoor-meter

本当は少しずつ切り分けた方が良いんだろうけれど、初動で全部入りにしたい衝動が出てこれの他に安めの防臭生ゴミ袋と300円で半年持つ事になっている消臭剤を突っ込んでみた。
クーラーボックスも計上すると、イニシャルコストが1万円でランニングコストが月数百円程度になる筈

**Comment by kachick** [comment]
クーラーショックを突っ込んだ直後からぐんぐん庫内温度下がっていくの眺めるの楽しい。高負荷対策をデプロイした直後から負荷が下がるサーバーを眺めているかの様だ

地味に便利だったのが、防臭ゴミ袋とか防臭剤みたいな定期的に交換する必要があるものを居れておけるポケットがクーラーボックスにあった所。発泡スチロールだとこうはいかなそう（中にいれれば良いような気もしつつ、もはやこの中は腐海というかdirty zoneだから純粋な状態では使えなくなってしまうのだ）

**Comment by pankona** [comment]
我が家も週に二回の回収であるが、蓋のついたゴミ箱を使って回収日まで保管というかそのままにしとけば、あんまり問題にならない気もするわよ

**Comment by kachick** [comment]
家の外で保管してる……？

中だとしたら、クーラーを強めにつけてるとか？
うちは我慢出来ないんじゃい 🙂‍↔️

**Comment by kachick** [comment]
![Screenshot_20240619-222906](https://github.com/kachick/times_kachick/assets/1180335/4596fa7e-46cb-4b61-b57a-92ccc250f5c6)

尚現在、室内クーラー無し28℃の中で生ゴミ入れ転生体ことクーラーボックスは13℃ぐらい。普通の保冷剤だけだと20℃ぐらいだったところからどんどん下がってこんぐらいで止まってるから、後は明日の昼ぐらいまで16℃以下をキープしてほしいところ
クーラーショックは予冷8時間なので、入れ替える余裕さえくれれば運用できる、筈

**Comment by kachick** [comment]
夕方～夜の経過時点で16.n℃になってるので、朝～昼には20℃ぐらいまで上がってそうな・・・・
室温28℃程度でこれだと、猛暑日にクーラーつけてない状態だとあっという間に死にそう

**Comment by kachick** [comment]
室温は24時間ほぼずっと28℃ぐらいで、庫内は朝(15時間程経過時点)に23℃ぐらいになってた
ここまで来るとかなり嫌な臭いがしてくるので、ドーバー パストリーゼ77とかいうのを注文してみた。ボックスへ突っ込む前にこれをぶっかけるようにする

一つ見落としてたのは予冷8時間というのはあくまで下限ということで、24時間冷凍庫に入れてあったクーラーショックを突っ込むとより庫内温度が下がって6℃ぐらいまでいった。
そこから上がりだしてるところに室内クーラーも付けて、まぁ夜まで20度以下は保てるだろうという感じ

今がソフトタイプなので、より効果があるらしいハードタイプのクーラーボックスに変えたい気もするけど、家にある使ってないクーラーボックスを～という動機から謎になるのでぐっと我慢している
何か使うなら凄いやすい発泡スチロールか、ワークマンの真空断熱スクエアを試したい。発泡スチロールだと防臭効果がなさそうな気はする

**Comment by kachick** [comment]
冷やさない生ゴミ対策としては 温度、湿度 が良く上がるけれど、湿度に関しては冷やす方向だと割とどうしようもないと思って無対策なんだけどなんかあるんだろうか。食品用シリカゲルでどうにかなる気はしないんだが

**Comment by pankona** [comment]
いや、我が家では室内に置いている。冷やしたりする工夫もしてないが、蓋しといて使うときだけ開ける、みたいので困ってないという気持ち。なにがプロブレムかって話かもしれぬな？臭いは大丈夫だがちょっとコバエが出たりはある...

**Comment by kachick** [comment]
コバエが出る状態だと割と生ゴミ臭キツイと思うんだけどなー

猛暑を迎えるにあたり粉家の生ゴミ入れが色んな虫に愛されるような祈りを込めておこう 🙏

**Comment by pankona** [comment]
あー、生ゴミをいちいちコブクロに包んで捨てているというワンホップがあるのがポイントなのかもしれない。
- シンクの脇に小さい袋を置いといて、普段の生ゴミはそこに捨てている
- なんとなく溜まったら蓋をして可燃ゴミ（蓋付き）に捨てる
- 次のコブクロをしつらえる

めんどくさがって可燃ゴミにいきなり生ゴミを投入することもあるけど稀である。だから臭いもコバエも気にならないのかもしれねえ、という考察

**Comment by kachick** [comment]
うちも生ゴミは小袋使ってて、基本一日一袋なんだけど結局まとめた先で死んでたんだよな…
2円ぐらいのポリ袋から5−10円の消臭袋に変えてみる(前使ってたけど冬場にやめてた)

**Comment by pankona** [comment]
単にわいが匂いに鈍感であるという説が出てきたな…

**Comment by kachick** [comment]
コバエが湧くという視覚での観測結果は同じなことを考えるとその疑いはある

**Comment by kachick** [comment]
https://www.irisplaza.co.jp/index.php?KB=SHOSAI&SID=7251832

使わない時期に邪魔すぎではと思わなくもないけど、1.5万ぐらいで買えるただの小型冷凍庫の方が良かった感はある。
誰かに僕のソリューション(生ゴミ付き)を売りつけて、その代金を充当してこれ入手したい……

**Comment by kachick** [comment]
まだまだ暑いとはいえもう8月も末なので一旦振り返ると、うまくいっている感はある。家の中にコバエや異臭が湧いたりはしてない(鼻が慣らされて曲がった可能性は否定できないけど)

>湿度に関して

これはでかくて安い湿気取りを入れてみたけど、たしかに湿気は取るものの保冷バッグ内の冷却効率落ちてそうだし効果も謎だった。残容量あったけど使わなくなってしまった。

>ドーバー パストリーゼ77

そもそも温度管理もどんだけ意味があったか謎なぐらい、こいつに成果が依存してる気がする。使いだしてからピタッと問題収まった感で、他の対策一切いらなかったのでは疑惑が若干・・・

でかいの買ったからまだ残ってるし、便利な商品を知った。
無理やりマイナスポイントをひねり出すと

- 総量はかなり残ってても全体の半分ぐらいからやたら出が悪くなってくる
- 火気厳禁なでかいボトルを台所付近に置くの不安
- 茶からの抽出成分なのか色が工事中に濁った水道水みたいな感じでちょっと嫌

**Comment by kachick** [comment]
> 温度管理もどんだけ意味があったか謎

という気持ちで、残暑まっただ中に保冷剤の交換さぼったらそれなりに臭ってきたので両翼が必要だった
