### ISSUE TITLE
2024-09-02 - Zettelkasten に興味はあるけど億劫で始めてすら居ない

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#305]
ref: https://github.com/kachick/dotfiles/issues/729, https://github.com/kachick/dotfiles/pull/748, https://github.com/kachick/times_kachick/issues/301

Zettelkasten というメモ取りというか知的生産術みたいなのがある。
メモツールを検討している中で知ったんだけど、なんか後から情報を引っ張りやすくするために入力時に整理整頓頑張るイメージが強くて食指がそんなに動いていない
自分は本当にただ書きなぐっといて後から目的のを引くのは現代ならツール任せで良いやろと、とにかく関連ワードを本文に書き殴っていればタグすら要らんと思ってる節があるのでなんか大変感がぬぐえない(強いて言うならタイトルと本文ぐらいは分けてもいいと思う。そしてタイトル長くする)

**Comment by pankona** [comment]
scrapbox が好きだがどうか

**Comment by kachick** [comment]
良さげなんだけど、正直機能としてはGoogle keepでも困ってないから同じくクラウドに閉じてセルフホストも出来ないなんかしらに移行したい気がなく……
やっぱシンプルなテキストフォーマットで管理してローカルとかGit管理で済ませたいんよな

**Comment by sat0yu** [comment]
obsidianいかがでしょうか。ローカルファイルなので任意のコマンドで検索できて便利

**Comment by kachick** [comment]
https://github.com/kachick/dotfiles/pull/748 で候補に入れてたんだけれど、実際試したことなかったので試してみました！

確かにすごい使いやすい感・・・そしてOSSではないけれど個人利用無料でファイルフォーマットがmarkdownならそこまで気にしなくてもよさそう
しかし Electron で作られているようで、[Wayland 上だと vscode 同様IMEが使えない](https://github.com/kachick/dotfiles/issues/689)という問題ががが(Chrome129には入ったけれど、ElectronがChromiumアップデートしてそのバージョンをobsidianが使いだすまで待つ必要がある)

**Comment by kachick** [comment]
* 別にコンソールで毎回書きたいわけでもない。使えれば便利なこともあるけれど、ブラウジングした際のURLを控えたいことも有り、どうせブラウザは開いている。そしてコンソール操作途中にIMEでの日本語切り替えが挟まるといろんなことが億劫になる。主がブラウザ経由、副がエディタだと理想

* 別に Markdown でがっつり書きたいわけでもない。そういうしっかり目の情報は他に清書(他の人からすると走り書きレベル)すればいいので、どちらかというとただのプレーンテキストを書き溜めておきたいだけ

* クラウドSyncは簡単なら簡単な程嬉しい。Git管理って良さげだけど、メモ書きの conflict 解消みたいなのがそれなりに発生すると嫌だ。特に一時的にオフラインでしかかけない環境とかで発生しがち

等々、つまりは現状の Google Keep がちょうど良すぎるみたいな話になるけど、これはこれでKeepの外へデータをエクスポートしづらい(有志拡張的なので出来なくもないし、全体バックアップみたいなのはできるが)という大きなのがあって結局どこを妥協するかみたいなとこはある

**Comment by kachick** [comment]
同じことは Google Documents でもあり、Driveとかとの連携が楽でよく使ってしまうがこの手のフォーマットで書くとローカルへデータが残らないので結局後からエクスポートの事考えるの億劫になって囲い込まれがち

**Comment by kachick** [comment]
github の wiki にまとめを書く(許容範囲) & テンポラリなのは google keeps に書く(やめたいけど便利すぎる) とやってて後者だけなんとかしたい気もしつつ面倒なので一旦いいかな・・・
