### ISSUE TITLE
2024-10-09 - Android の provisioning

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#309]
* 設定項目がどこにあるか覚えてなくても、単語で設定画面から検索すれば大体見つかる
* メモるのが面倒でもとりあえずスクショ取りまくっておくと後でフォトから身を助ける
* 機種変更した後古い機種が手元に残るときはどっちも同じ設定にしたいものの面倒なので、これを機会と移行前に済ませておくのが理想
* SIMの通話が働くことを確認する
* WiFi や他のSIMを disabled にした状態でSIMの通信を確認しておく。通話は確認漏れることほぼないが、通信はAPN設定漏れでもインジケーター正常な上に自宅だとWifi経由で通信してたりするので外でてからマップ使えなくて死んだことが有る
* Android の更新。同梱の説明書にはまずMNPの仕方が書いてあるけど、とりあえず上げとく。しかし移行元よりバージョン古い状態で移行ツール走らせるとかおっかなくね？
* 古い端末側だとなんか頑張った結果ニュースのリンク開くのもfirefoxに出来てたんだけど、新機種で再現できない。OS同じなのに……スマホもdotfilesで管理してぇ

やること | 理由とか | 新機種へコピー可？
--- | --- | ---
デフォルトブラウザを Chrome から Firefox へ切り替える | 拡張が使えるから。[Chromeも使えるようにしだすらしいけど実機上は相変わらずだめにするっぽい](https://www.androidauthority.com/desktop-chrome-android-extensions-3488455/)。そもそもスマホ上だとアカウント切り替えしづらいから Chrome であるメリットが少ない | ✅ 
ジェスチャー => 電源ボタンを長押し => s/デジタルアシスタント/電源ボタンメニュー/  | 電源ボタンには電源機能を期待する | ❔  
キーボードを調整 | キーボード系は僅かな差異でもずっとストレスになる | ✅
指紋認証登録 | 面倒でも両手から一本ずつはやっとく | ✖️ 
Firefox URLショートカット作り直し | Firefoxは公式にPWAサポートしないものURLショートカットは簡単に作れた | ✖️ 
MFA アプリのデータ移行 | クラウドバックアップ非対応系だとかなり面倒だけど今のは大体できる | △
金融機関系 アプリのMFA移行 | 漏れがち且つ面倒な印象 | ❔  
s/ジェスチャーナビゲーション/3ボタンナビゲーション/ | 古いUIから移行できない。これが老い・・・ | ✅
モバイルSuicaの残高移行 | 連携自体はしっかりしてるので誘導してくれる | △
リアルタイム翻訳をoff | 便利なときもあるのかもだけど、常時テキスト浮かんだ印象で嫌  |  ✖️ 
eSIM 移行 | eSIMの方が諸々簡単というか便利なイメージあったんだけど、機種間移行が簡単には出来ないし場合によっては手数料かかるらしいので、デュアルで対応って殆どなさそうだけど物理SIMのが楽な気はする  |  ✖️ 
タイルの編集 => ライト、VPN、インターネット、自動回転、サイレント/機内/おやすみ モード | 緊急時にパニクる機能を入れておきたい。ライトは使うというより間違って点いたものを消したい事が多い。回転も基本固定 | ✅

**Comment by kachick** [comment]
前機種と同じメーカーで同じ色のスマホケース買ったら似すぎててしょっちゅう取り違える。とうとう間違った方持って外出してしまった。

esim移行で手間取ってるのがむしろ幸いと出たけど、今更Pasmoのデポジット新規に支払うことになった。古い端末は封印出来るまで家の中でケース外しておくと良さそう

**Comment by kachick** [comment]
古い方にシール表裏貼っておいたのにまた間違えて持ってきてしまった……家の中だと判別つくのに急ぐと間違える

扱い雑だし古い方も便利でケースつけたままkindle読んだりに使ってたけど、ついやってしまうのでeSIM無効にしておくか……（外出てすぐマップ使ってる時に問題無いから気付けない）

**Comment by pankona** [comment]
👴
