### ISSUE TITLE
2024-12-12 - キーボード配列を US-ASCII から JIS に戻してみようとしたけれどこれはこれで大変だった 

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#318]
ずっとJIS配列を使っていたのに10年ぐらい前macbookを買う時US配列を選んでからそのままUS配列を使ってきていた。
しかし単発でAltを押した時にIMEの切り替えと扱うみたいなのにソフトウェアを介すのが嫌というかまずそこを乗り越えないと何も始まらないのが凄い面倒に感じがち。
やはりキー数が揃ってるJISの方が日本語入力必要なときは自然なんでは？と、ブラックフライデーでキーボードの類も安くなっていたのを機に、US配列で愛用しているのと同じサイズのJIS配列キーボードを買って使いだした。

US配列信奉に洗脳されていただけではと自分を疑っていたんだけれど、実際戻してみて不便に感じるとこもある
JISしか使ってなかった頃は気にならなかったはずなので単に慣れの問題なのか

- スペースバー短い
- エンターが遠い(US配列よりデカくなるから押しやすくなるんではと思ってたら、縦に延びても横に短いのでむしろ押しにくい)
- 変換・無変換で切り替えしていると使わないのに、Escの近くにあって押しがちなE/Jが邪魔
- 記号の類が混乱する。単にUSと違うというよりUS配列がいい感じだったのか。特にシングルクォート、ダブルクォートが全然違う場所にあるのなんでやねんとなる
- HelixやVimでコマンドに入る時の : が今までと違う！というのが頻度的には辛い。しかしShift不要だしこれに関しては慣れればJIS配列の方が便利なのでは
- ハードウェアリマップ機能があればいくらでもなんとかなるだろと思ってたけど、それやると結局付属キーキャップガン無視になるので微妙かも
- 増えて嬉しいと思ってた Henkan / Muhenkan も今度は Alt 使いたい時に混乱するし、なんなら Super 押す時にも混乱してしまう
- Windows はデフォルトだと再起動するまでUSとJISキーボードのレイアウト変更できなくて大変すぎる

半田付け出来る気がしないから避けてるけど、自作キーボードがこれだけ人気なのも何となく分かる気はしてきた

ref: https://github.com/kachick/dotfiles/commit/9a487555481d461d4c841e114c863e2dc08b0e37

**Comment by pankona** [comment]
vimrc で ; と : を入れ替える仕草、しばしばあると思います。わいもUS使いではあるが、US配列に呪われてると選べるノートPCとか激減するんで、JISに慣れたい気持ちはちょっとある。

**Comment by kachick** [comment]
https://note.com/kamemushi_works/n/n65ab71ca98ec

オーストラリア英語配列気になる

**Comment by kachick** [comment]
このまま頑張って JIS に体を慣らすのもなんか違うなぁと結局元のキーボードに戻してしまった。
余ったJISキーボードをどうすりゃいいのか。緊急時用にと1,2個持ってたけどこの大きさのが浮いてても嬉しいこと等特に無い

尚 買ったのは Keychron K3 Max というやつで使い心地自体は凄い良かった。US配列に替えてほしい・・・
