### ISSUE TITLE
`嫌われる勇気` と `幸せになる勇気` のAudible、他アドラー心理学系の書籍を読んだりした上での感想文

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#39]
## TL;DR

* foo
* bar
* baz

## 何についてか / About

ref: link, link

## 経緯 / History

1.
1.
1.
1.
1.
1.

## 結論 / Conclusion

* foo
* bar
* baz

**Comment by kachick** [comment]
[ティール組織](https://www.amazon.co.jp/dp/4862762263) も読んだときはかなり興奮したので、 https://business.nikkei.com/atcl/gen/19/00087/030200184/ はかなり興味深く読んだ。

>承認欲求の低い人を採用する

というのは、かなりインパクトのあるワードだなと思った。優秀そうな人にも承認欲求強い人は大勢居る気がするし、自分なんかでも優秀ではないが承認欲求はあるよなぁと思う。
が、言いたいことはわかる気もする。承認欲求低い人ばかりの組織だったら、確かに色々と運営が楽そうだ。考えさせられた。

**Comment by kachick** [comment]
読んでから半年以上経過したらほぼほぼ忘れた感あるので close しちゃおう

**Comment by kachick** [comment]
自分のために下げなきゃ～というより「都度都度頭をもたげてくる承認欲求めんどっ！」と思う事が多くなってきたので https://github.com/kachick/eyes_away_from_github-popularity とか作ってみた。予想以上に心の平穏が保たれた

**Comment by kachick** [comment]
[老子のリポジトリですら生えてくる](https://github.com/nrrb/tao-te-ching/blob/1b00292518ee6e477773c40424fdb5f90bf7035e/README.md?plain=1#L5)ので根源的な何かなのだろう

https://github.com/kachick/depop/commit/085284a07f3af32f5745a79e00fc7b45ab2aa4f1

**Comment by pankona** [comment]
老子のリポジトリ、こんなんあるんやな、すごい

**Comment by kachick** [comment]
そも英訳の電子書籍が少ないのでこの手のリソース結構貴重という背景がある https://github.com/kachick/times_kachick/issues/205
