### ISSUE TITLE
Crystal 良さそうだなーとずっと思いつつ使ってこなかったが、 1.0.0 release 直前に色々キャッチアップした記録

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#4]
## TL;DR

* foo
* bar
* baz

## 何についてか / About

ref: link, link

## 経緯 / History

1.
1.
1.
1.
1.
1.

## 結論 / Conclusion

* foo
* bar
* baz

**Comment by kachick** [comment]
何も覚えてない・・・辛い。
shard のバージョン管理方針が厳しくなって各所で阿鼻叫喚みたいな感じはあった。
https://github.com/crystal-jp/introducing-crystal がとても良い資料で助かったんだけど、 https://github.com/EbookFoundation/free-programming-books に登録しようとした直前で、いや、これ別にフリーでは無いか・・・？となってぐっと留まった。でも良い資料なのでこれ見ながら再チャレンジしたい。Kemal 使いたいし、CLIもこれでワンバイナリにしたい。

ただついこないだそれで試そうとしたら libpcre が無いとかで躓いた。この手の話は前からあったようで、今 release には bundled みたいなのも含まれてるんだけど、asdf-crystal の対象がこっちじゃないので躓いた感。やっぱ初学者が初期段階で躓くとそのままになってしまいがち・・・

**Comment by kachick** [comment]
CLIから始めるのに慣れてる事もあって、丁度良いやと https://github.com/kachick/renovate-config-asdf のサポートツールは Crystal で書くようにした。
エディタのサポート的なのはまぁやっぱそこまで強くはないんだけど、それでも十分便利。丁度仕事で使ったことのある Ruby, TypeScript, Go あたりの いいとこ取りみたいな感覚で使えるのも合って、自分の性に合ってる。

**Comment by kachick** [comment]
久しぶりに少し触る機会があったけどコンパイル時間の長さに心が折れた・・・

**Comment by pankona** [comment]
やっぱコンパイル速いのは大事よな、わかる
何度も何度もやるからね、ちりつも

**Comment by kachick** [comment]
そうやって go が有利っぽい話の時だけ反応しおって・・・

でもまぁそんな感じ・・・逆にいうと CGO_ENABLED=0 が付いてて go の顔しつつ遅い時には好印象から反転しがち(理屈 https://stackoverflow.com/questions/47714278/why-is-compiling-with-cgo-enabled-0-slower とかちゃんと理解せずに嫌ってる節は否めない)
