### ISSUE TITLE
盛り上がるOSSには地味にロゴが大事だよなと思ってる話

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#49]
## TL;DR

* foo
* bar
* baz

## 何についてか / About

ref: https://micnncim.com/post/2019/12/08/make-oss-logo/, https://github.com/mobu-of-the-world/mobu/issues/72

## 経緯 / History

1.
1.
1.
1.
1.
1.

## 結論 / Conclusion

* foo
* bar
* baz

**Comment by kachick** [comment]
自分でも描きたい

**Comment by ohbarye** [comment]
描くのとはちょっと違いますが最近はフリーロゴ生成サービスでも普通に使えそうなやつが出てくるので、ラクして「ちゃんとしてる」感が出せそうだな〜と思ったりしてます

e.g. https://www.freelogodesign.org/

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1811616/175781525-d3db0c06-7ed4-4ec8-b7ef-fa816cb07fac.png">

**Comment by kachick** [comment]
おぉーすごい！ 最近流行りのAI画像生成的な物かと思ったけど、名前入力するだけで出てきたから単に合成してる感じ・・・？

でもなんも無いのよりはずっと良さそうですね！

**Comment by kachick** [comment]
vs 生成AI
---

### 採用

Copilot に僕の下書きを描きなおさせたりしてみた

https://github.com/kachick/depop/pull/96#issuecomment-2017858947

著作権的な話が面倒になると嫌なので、わたしはここからここまでAI使いましたよーというのを明示しながらディレクトリ構造でも分けるなりしている

### 不採用

![スクリーンショット 2024-02-22 135311](https://github.com/kachick/times_kachick/assets/1180335/786d0f38-2803-4c87-af8e-5e9880bb8f02)
![スクリーンショット 2024-02-22 135317](https://github.com/kachick/times_kachick/assets/1180335/96c9e869-e9c3-4786-88bf-177943c25d03)
![スクリーンショット 2024-02-22 141623](https://github.com/kachick/times_kachick/assets/1180335/fe04f558-0b91-47c8-aaf9-3329d2987b34)
![スクリーンショット 2024-02-22 155245](https://github.com/kachick/times_kachick/assets/1180335/6f366d2f-895a-4c3e-83a8-b9d90f9e7282)
