### ISSUE TITLE
2021-05-27 - `OSSごっこ` と言われたりもしたが、GitHub の `Organization` を自分達で作ってみたらかなり楽しいという話

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#86]
## TL;DR

* マイナーなプロジェクトだけど、仲間内では愛用しているみたいなリポジトリを GitHub の Organization 化してコアメンバーに収まったら結構楽しい。

## 何についてか / About

ref: https://github.com/mobu-of-the-world/mobu

## 経緯 / History

1. これは元々 Quipper の同僚である @pankona さんが2019年末 Web Frontend の手習い的に始めた小さなOSS
1. 自分の基礎技術力やCSS力は彼よりずっと低いが、当時は TypeScript やら React というレイヤーでは自分の方が若干得意(どんぐりの背比べだけど)だったことと、ユーザーが誰も居ない事とか Author が追加したいと思っている機能がまぁかなり簡単で、初学者レベルには逆に「やりがい」が感じられ[ポンポンPR投げたりしていた](https://github.com/mobu-of-the-world/mobu/pulls?q=is%3Apr+author%3Akachick)。自分のレベルからみて程よいというか、「全てわかっているわけではないがちょっと頑張ると実現出来そう」みたいな課題に取り組んでいる時というのはやっぱり楽しい。
1. まぁ機能的にも実装的にも、おそらく Web Frontend に強い人がみたら失笑物なのだろう。まず[未だにtestがない](https://github.com/mobu-of-the-world/mobu/issues/61)、[テストがないコードはレガシーコード](https://www.shoeisha.co.jp/book/detail/9784798116839)らしいので、生まれてから今までずっとレガシーコードである。
1. ただそれでも社内でモブプログラミングするときに、あれこれ愚痴を言いながらも使ったりしていた「仲間内愛されOSS」であった。
1. アクティブな更新はしばらく止まっていたが、つい先日ふと思いついて[「GitHub の Organization 化」を提案して Approve してもらった。](https://github.com/mobu-of-the-world/mobu/discussions/53) マイナーな OSS 1 repository で何が Organization だよという話ではあるが、ぶっちゃけ自分が GitHub の Organization 機能を色々試したいとかその程度のネタに使わせてもらおうと思ったのだ。あと、幾つかの Organization に所属したことはあるがヒエラルキー的には最下層しか経験した事がないので、一度「頂点からの景色」を観てみたかった。
1. で、[まぁまずはロゴだよね](https://github.com/kachick/times_kachick/issues/49)、ということで[ロゴを設定した](https://github.com/mobu-of-the-world/mobu/issues/72)。
1. その後[チーム](https://github.com/orgs/mobu-of-the-world/teams)を作った。2人しか居ないので2人共メンテナである
1. そしたらこの悪ノリにノッてくる感じでポンポンと社内からPRを投げてくれる人が増え、うむ、君はある程度のコントリビューションをポイントを溜めたな、よかろう。みたいな感じでコミッターにして行った。中には [CRA(Create React App) に backport](https://github.com/facebook/create-react-app/pull/10763)された[PR](https://github.com/mobu-of-the-world/mobu/pull/73#issuecomment-811490887)まであって正直笑ってしまった。
1. やはり人は信頼されると信頼に応えるところがところがあるのか、コミッターになった方々は積極的に開発に参加してくれていて、正直自分が何時まで共同創業者という理由だけでメンテナに収まり続けられるか怪しい状況である。
1. ちなみに自分としては、せっかく Organization 化したのに 1 repository だと寂しいなという気持ちと [Elm](https://github.com/elm) ユーザー増えると楽しそうみたいな気持ちがあって、 #53 が終わったら Elm 版を作ってこの Organization の 1 repository にしてみたいなと考えては居る。そうすれば完璧に Author の一人なので、追い出されることも無いだろう。終身独裁保証である。

## Note

この「成功」は Original Author の人柄に依るところも大きいと思う。まぁ、かなり人望があるというか人に好かれるタイプであるというのに加えて、このリポジトリに対する「細かい話への強いこだわり」的なのが無かったと言うか。自分だったらどうだろうか？ :star: 0 の PJ でも、 [rubocop の設定を細かく設定しそうなタイプ](https://github.com/kachick/ruby-ulid/blob/6cf828199774dac022c7689fa4d849a4db973eae/.rubocop.yml)なので、なかなか難しいかも知れない。

---

<img width="962" alt="スクリーンショット 2021-05-27 9 36 51" src="https://user-images.githubusercontent.com/1180335/119749431-10406f80-bed2-11eb-939f-f27bfe1bc72a.png">

ちなみにいま現在の[チーム](https://github.com/orgs/mobu-of-the-world/teams)構成状況はこんな感じだが、別に外部コントリビューターお断りということではなく、割と真面目に「OSSごっこ」をしているのでPRウェルカムで、その結果コミッター、果てはメンテナになれるかもしれないので是非よろしくという感じである。[公用語も英語だし](https://github.com/mobu-of-the-world/mobu/discussions/48#discussioncomment-537234)。

**Comment by highwide** [comment]
(「OSSごっこ」)[from: https://quipper.slack.com/archives/CJLHMEW7Q/p1620480822353200]って言ってしまったけど...僕もmobu活動を楽しんでいます、素敵な場をありがとうございます〜！

> 「全てわかっているわけではないがちょっと頑張ると実現出来そう」みたいな課題に取り組んでいる時というのはやっぱり楽しい。

本当にこれです！
